name = "opencompanybot"
main = "main.py"
compatibility_date = "2026-02-11"
compatibility_flags = ["python_workers"]

account_id = "35ae7776e494993cad13e4df0a906efe"

[env.production]
name = "opencompanybot-prod"

[build]
command = ""
cwd = "."
