name = "opencompanybot"
main = "main.py"
compatibility_date = "2026-02-11"
compatibility_flags = ["python_workers"]

account_id = "35ae7776e494993cad13e4df0a906efe"

workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "opencompanybot"
database_id = "adce1d6c-5137-4703-bdc1-7807ab5a67c7"

[env.production]
name = "opencompanybot-prod"

[build]
command = ""
cwd = "."
